# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 12:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter Battle Name', max_length=52, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Enter Year', max_length=3, null=True)),
                ('attacker_king', models.CharField(blank=True, help_text='Enter attacker king', max_length=24, null=True)),
                ('defender_king', models.CharField(blank=True, help_text='Enter defender king', max_length=24, null=True)),
                ('attacker_1', models.CharField(blank=True, help_text='Enter attacker 1', max_length=27, null=True)),
                ('attacker_2', models.CharField(blank=True, help_text='Enter attacker 2', max_length=9, null=True)),
                ('attacker_3', models.CharField(blank=True, help_text='Enter attacker 3', max_length=7, null=True)),
                ('attacker_4', models.CharField(blank=True, help_text='Enter attacker 4', max_length=6, null=True)),
                ('defender_1', models.CharField(blank=True, help_text='Enter defender_1', max_length=16, null=True)),
                ('defender_2', models.CharField(blank=True, help_text='Enter defender_2', max_length=9, null=True)),
                ('defender_3', models.CharField(blank=True, help_text='Enter defender 3', max_length=10, null=True)),
                ('defender_4', models.CharField(blank=True, help_text='defender 4', max_length=10, null=True)),
                ('attacker_outcome', models.CharField(blank=True, help_text='Enter attacker outcome', max_length=4, null=True)),
                ('battle_type', models.CharField(blank=True, help_text='Enter battle type', max_length=14, null=True)),
                ('major_death', models.IntegerField(blank=True, help_text='Enter major death', max_length=1, null=True)),
                ('major_capture', models.IntegerField(blank=True, help_text='Enter major_capture', max_length=1, null=True)),
                ('attacker_size', models.CharField(blank=True, help_text='Enter attacker size', max_length=6, null=True)),
                ('defender_size', models.CharField(blank=True, help_text='Enter defender_size', max_length=5, null=True)),
                ('attacker_commander', models.CharField(blank=True, help_text='Enter attacker commander', max_length=95, null=True)),
                ('defender_commander', models.CharField(blank=True, help_text='Enter defender commander', max_length=109, null=True)),
                ('summer', models.CharField(blank=True, help_text='Enter summer', max_length=1, null=True)),
                ('location', models.CharField(blank=True, help_text='Enter location', max_length=36, null=True)),
                ('region', models.CharField(blank=True, help_text='Enter Battle Name', max_length=15, null=True)),
                ('note', models.CharField(blank=True, help_text='Enter note', max_length=257, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter King Name', max_length=30, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('rating', models.FloatField(default=400)),
            ],
        ),
    ]
